### ISSUE TITLE
lld_encoder.с название функций

### ISSUE THREAD

**Issue by KaiL4eK** [serykhelena/wr8_2019#10]
https://github.com/serykhelena/wr8_2019/blob/845de2d2feea6ec3a5e5c7d0b3c312e22e3e98aa/src/lld_encoder.c#L50

Функции не отражают классификации модуля как LLD - LowLevelDriver

**Comment by KaiL4eK** [comment]
Как результат, не так просто оценить, чо за источник информации при использовании функций из https://github.com/serykhelena/wr8_2019/blob/development/include/lld_encoder.h

**Comment by OlegAProject** [comment]
добавил всем функциям приставку с определением модуля, которому они принадлежат
