### ISSUE TITLE
Назначение функции в модуле lld_wheel_rotate

### ISSUE THREAD

**Issue by KaiL4eK** [serykhelena/wr8_2019#13]
https://github.com/serykhelena/wr8_2019/blob/845de2d2feea6ec3a5e5c7d0b3c312e22e3e98aa/include/lld_wheel_rotate.h#L22
Для чего используется данная функция? Для чего может использоваться диапазон поворота [-100; 100]?

**Comment by OlegAProject** [comment]
убрал, не в той карточке в трелло посмотрел задание
