### ISSUE TITLE
Функция получения прямого значения с АЦП с фильтром lld_wheel_rotate.h

### ISSUE THREAD

**Issue by KaiL4eK** [serykhelena/wr8_2019#14]
https://github.com/serykhelena/wr8_2019/blob/845de2d2feea6ec3a5e5c7d0b3c312e22e3e98aa/include/lld_wheel_rotate.h#L16
Может имеет смысл завести функцию получения значения без фильтра? Сейчас нет возможности получить чистого значения с АЦП, насколько я понял по функциям

**Comment by OlegAProject** [comment]
добавил функцию lldSteeringControlGetAdcVal
