### ISSUE TITLE
Добавить к правилам разработки

### ISSUE THREAD

**Issue by KaiL4eK** [serykhelena/wr8_2019#17]

**Comment by KaiL4eK** [comment]
При разрешении issue не забывайте присваивать его себе, если оно ранее уже не присвоено, чем обозначите, что вы беретесь за его исправление. Также по возможности необходимо классифицировать issues с помощью лейбла.

**Comment by KaiL4eK** [comment]
Эмм, в этом репо есть правила) docs/dev_rules.md, в шаблон не надо)

**Comment by serykhelena** [comment]
Упс, не заметила, не так поняла (=
