### ISSUE TITLE
Комментарии к коммитам

### ISSUE THREAD

**Issue by KaiL4eK** [serykhelena/wr8_2019#3]
Ну никак не отражена суть коммитов в названиях к 917cf7b92f079a253806acc01e9f652509ff28db, 42aefa603404c19e5a76f9a81ecce3349cdbb313, 2493386297e8e5a1c763ab02022b0e5a092fe764.
В комменте 92a4b7e6da22e2b6d1fc47177815d1e81bb97e21 не понятно, что за модуль в одну строку.

**Comment by OlegAProject** [comment]
вроде всё что нужно , поменял и добавил
