### ISSUE TITLE
Добавить комменты к функциям в lld_encoder

### ISSUE THREAD

**Issue by serykhelena** [serykhelena/wr8_2019#33]

**Comment by OlegAProject** [comment]
немного не понял где не хватает комментов, в хэдере вроде всё прописал

**Comment by serykhelena** [comment]
В с-файле

**Comment by OlegAProject** [comment]
добавил комментарии, но на 100% не уверен что так надо было, поэтому дождусь проверки, пока что не закрываю issue

**Comment by serykhelena** [comment]
Можешь как пример использовать тигру https://github.com/KaiL4eK/tigra_project/blob/develop/controller_driver/src/lld_control.c 
По сути там дублируются комментарии из h-файлов (=

**Comment by OlegAProject** [comment]
сделано
