### ISSUE TITLE
Почистить ветки

### ISSUE THREAD

**Issue by KaiL4eK** [serykhelena/wr8_2019#40]
Те ветки, которые уже отжили свое (фича реализована / баг закрыт) лучше удалять как локально, так и на сервере

**Comment by AnastasiaRudikova** [comment]
У меня осталась только ветка, над которой я работаю, RemoteControl и ветка development. 
Остальные ветки, над которыми я работала, удалены.

**Comment by serykhelena** [comment]
Думаю, пока что можно закрыть эту issue, после тестирования уберём лишние ветки
