### ISSUE TITLE
[test_lld_encoder.c] Пофиксить бы выравнивание

### ISSUE THREAD

**Issue by KaiL4eK** [serykhelena/wr8_2019#43]
https://github.com/serykhelena/wr8_2019/blob/908d7c12a3d5864b845e22e8b29bad2a73bc2915/tests/test_lld_encoder.c#L77
https://github.com/serykhelena/wr8_2019/blob/908d7c12a3d5864b845e22e8b29bad2a73bc2915/tests/test_lld_encoder.c#L69
https://github.com/serykhelena/wr8_2019/blob/908d7c12a3d5864b845e22e8b29bad2a73bc2915/tests/test_lld_encoder.c#L21

**Comment by OlegAProject** [comment]
заменил табы на 4 пробела
