### ISSUE TITLE
[common.c] Стало пустым?

### ISSUE THREAD

**Issue by KaiL4eK** [serykhelena/wr8_2019#44]
Я так понял, он опустел? Оправдано ли, если, например, потребуется обработать нажатие кнопки - доставать конфиг EXT из энкодера?

**Comment by serykhelena** [comment]
На данный момент общих модулей не было. Сейчас Олег в своей ветке будет добавлять туда конфигурацию АЦП. Я предложила не засорять этот файл пока не будет необходимости. Просто чтобы избежать путанницы (=
