### ISSUE TITLE
[lld_control.c] Эм, тут какая-то путаница случилась с назначением =)

### ISSUE THREAD

**Issue by KaiL4eK** [serykhelena/wr8_2019#51]
https://github.com/serykhelena/wr8_2019/blob/908d7c12a3d5864b845e22e8b29bad2a73bc2915/src/lld_control.c#L118
Во-первых, steering - поворотные, и они не через ESC работают =) Во-вторых, кажется для поворотных колес нужны разные параметры преобразования. А для ходовых - не надо, вывод: не перепутаны ли функции?))

**Comment by OlegAProject** [comment]
мисклик с номером коммита, исправил 50й

**Comment by KaiL4eK** [comment]
То есть, фикс сделан?
