### ISSUE TITLE
Перенести define с диапазонами для управления приводами

### ISSUE THREAD

**Issue by serykhelena** [serykhelena/wr8_2019#53]
Поскольку диапазоны будут использоваться и в Remote Control, то целесообразно перенести эти дефайны в common.c

**Comment by serykhelena** [comment]
При этом дефайны для коэффициентов должны высчитываться в функции инициализации

**Comment by AnastasiaRudikova** [comment]
я коэффициенты оттуда вообще уберу, сейчас пишу формулы, чтоб автоматически считалось в lld_control

**Comment by serykhelena** [comment]
Отлично, когда всё сделаешь, только тогда закрывай issue (:

**Comment by serykhelena** [comment]
@AnastasiaRudikova , почему в common.h то ?
