### ISSUE TITLE
Перевести вывод в терминал на dbgprint()

### ISSUE THREAD

**Issue by serykhelena** [serykhelena/wr8_2019#62]
Везде, где не нужен вывод в матлаб - выводить через SD3 (dbgprint)

**Comment by KaiL4eK** [comment]
@serykhelena, можешь поподробнее описать, почему вывод в матлаб должен делаться функцией строкового вывода для отладки?

**Comment by serykhelena** [comment]
Почему же? Я не очень понимаю о чем ты... я подразумеваю, что в матлаб вывод идёт через sd7, с помочью функции sdWrite()
